apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BlockObjectsOfType
metadata:
  name: disallow-basic-auth-secret
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Secret"]
  parameters:
    forbiddenTypes: ["kubernetes.io/advance-auth", "kubernetes.io/basic-auth", "kubernetes.io/ssh-auth"]
