apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: must-have-cost-center
spec:
  match:
    kinds:
      - apiGroups: ["redis.cnrm.cloud.google.com"]
        kinds: ["RedisInstance"]
  parameters:
    labels: ["costcenter"]
